### ISSUE TITLE
set legend to display open for 0.5 - 1 seconds on page load

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#123]
the legend could be more obvious to a new user. a simple solution would be to set it to display as open for 1-2 seconds on page load, and then auto-close. Users will then know exactly what options are available to them.

this function is already set for the + (create new gather/resource) right now so you can probably just copy the code directly across

**Comment by AndyatFocallocal** [comment]
update: i think this works better set at just 1 second, or even 0.5. we just want to the user to see that it is there

**Comment by Spartano** [comment]
I have made some tests. For slower connections it never shows, thats why i
set it open. I have tryed with 5 seconds and still doesnt give good
results. If ypu wish i will set it up to 1 sec.

Il 21 Feb 2017 23:45, "AndyatFocallocal" <notifications@github.com> ha
scritto:

update: i think this works better set at just 1 second, or even 0.5. we
just want to the user to see that it is there

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/focallocal/fl-maps/issues/123#issuecomment-281507089>,
or mute the thread

**Comment by AndyatFocallocal** [comment]
I think it's a bit obtrusive the way it it's. Tbh, I'm not totally sure, but I'd favor occasionally not showing over always irritating a user

**Comment by Spartano** [comment]
I will set it to 1 sec then

Il 22 Feb 2017 11:44, "AndyatFocallocal" <notifications@github.com> ha
scritto:

**Comment by AndyatFocallocal** [comment]
:)
