### ISSUE TITLE
add country/city filter so users can find gathers in their city easier in list view

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#24]
i just remembered how absolutely amazingly cool it looks when you click an item in the list view

**Comment by ydaniel98** [comment]
@AndyatFocallocal I was about to take on this one, but I am unable to add events. I am getting a "Please provide an address" error when everything is filled out (new event form). Is this a known bug?

**Comment by AndyatFocallocal** [comment]
yes, i noticed this recently, it has developed in the last few updates.

i don't think i've created an issue for it., would you like to add it to the issues/bugs list, and assign it into the milestones for reaching the Beta launch Daniel

**Comment by AndyatFocallocal** [comment]
@ydaniel98 feel welcome to tackle any issue and this is a cool one to get done, in case you hadn't seen the milestones, these are the issues needed to reach our Beta Launch: https://github.com/focallocal/fl-maps/milestone/1

**Comment by ydaniel98** [comment]
@AndyatFocallocal I took some time this morning and couldn't find a cause. I will add the events manually to get the filter done and then I will tackle the bug.

**Comment by ydaniel98** [comment]
@AndyatFocallocal I finished the UI for the filter but ran into a small problem. (The delete icon is just a placeholder)
<img width="1277" alt="screen shot 2016-12-27 at 1 20 20 pm" src="https://cloud.githubusercontent.com/assets/11820758/21504813/641156c4-cc38-11e6-816b-75ff43c55eeb.png">

In order to filter events by country or, city, the country and city would have to be fetched per event from the address. This might lead to some performance issues. However adding the country and city directly when the event is created could solve this issue. Would modifying the database be a possibility? I figured that a modifying the db would be a team desition.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 the best thing to do would be to discuss this in the Slack channel, and to tag Pawel and Dx who are both doing some coding this week

**Comment by AndyatFocallocal** [comment]
@ydaniel98 as a user using the map in a smaller town in say South Africa, i'll want to be able to find events near me the as easily as someone in New York. can we make that possible in the filters you're building?

**Comment by ydaniel98** [comment]
@AndyatFocallocal Yes. I am planning on having 4 possibilities for the filter - country, state, city and any other thing that one could have searched for in the search input. Will that be sufficient?

**Comment by AndyatFocallocal** [comment]
Yes, sounds great :)

**Comment by ydaniel98** [comment]
@AndyatFocallocal  I created a pull request for this issue.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 sorry foe the wait, i'm just asking the others to talk me through the process. i'm afraid i'm still learning Github

**Comment by ydaniel98** [comment]
@AndyatFocallocal You already merged the pull request 2 days ago.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 ah yes, i had a notification so i clicked it. tbh i should've asked the others to do so as i'm not able to review code in Meteor
