### ISSUE TITLE
Add home page sections

### ISSUE THREAD

**Issue by royGil** [focallocal/fl-maps#545]
Open http://gather.focallocal.org/home, you'll see that that the home page contains several sections ("what is focallocal", "what adventures await me?", etc...)

Those sections should be re-implemented into the react version.

**Keep in mind:**
There will be 2 versions of this application (with different text) so you should build those sections using strings from the i18n file.
You can see what I'm talking about by looking at http://gather.focallocal.org/home and on http://brightertomorrowmap.com/home.

If you are not sure what I'm talking about - just create the sections with strings hard-coded and later i'll update the components to take the strings from the i18n file.

**Comment by ydaniel98** [comment]
@royGil Originally, the home page was made using react - I had to translate it to blaze. So this is already done. We just have to add i18n to it. I'll see if I can find the repo from the dev who made it.

**Comment by ydaniel98** [comment]
Here it is. https://github.com/focallocal/fl-home/tree/2c773e12bf25a3117d9a69d9de8eaa853e854f08

**Comment by AndyatFocallocal** [comment]
Yes, just need to drop the text from the current one in and the Megamenu

**Comment by HuascarMC** [comment]
I took the home components in the [commit](https://github.com/focallocal/fl-home/tree/2c773e12bf25a3117d9a69d9de8eaa853e854f08) that Daniel posted and added them to the react version in this [branch](https://github.com/HuascarMC/fl-maps/tree/home-page-sections/imports/client/ui/pages/Home). They all render well, just need to plug in the SCSS and it should be ready.

**Comment by AndyatFocallocal** [comment]
Well done, would you like to submit a pull request to merge it into the new
build?

On 19 May 2018 09:01, "Huascar" <notifications@github.com> wrote:

I took the home components in the commit
<https://github.com/focallocal/fl-home/tree/2c773e12bf25a3117d9a69d9de8eaa853e854f08>
that Daniel posted and added them to the react version in this branch
<https://github.com/HuascarMC/fl-maps/tree/home-page-sections/imports/client/ui/pages/Home>.
They all render well, just need to plug in the SCSS and it should be ready.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/focallocal/fl-maps/issues/545#issuecomment-390387934>,
or mute the thread
