### ISSUE TITLE
CSS improvements in listing popup window

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#564]
![image](https://user-images.githubusercontent.com/16229696/40363714-467c0b5e-5dc8-11e8-97fd-dc203c333899.png)

'when' should be in a list so users can read it easier. 

text in the details section slightly larger for users with poor eye sight - font-size: 17px; on blockquote

**Comment by royGil** [comment]
A list will be available only on the event page because otherwise you might get a huge window if the event has a long description/when fields, I want to keep this as minimal as possible.

People with poor eyes can actually use the zooming option that the browsers provide - bigger font will break the layout of this window.

What do you think?
