### ISSUE TITLE
Explore why the 'Partners' page isn't loading in either branch.

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#902]
Here is the page which should be loading: https://github.com/focallocal/fl-maps/blob/master/imports/both/i18n/en/partners.json

and here is the page which is loading: https://focallocal.org/partners

Clue! the title in each branch says 'partners'. i just changed i18n master to match/ fl-sleeper still says 'members' yet 'partners loads on the live page. Neither live page says 'members'. Where is the live page taking that title 'partners' from if not from i18n??

https://brightertomorrowmap.com/partners

https://github.com/focallocal/fl-maps/blob/fl-sleeper/imports/both/i18n/en/partners.json

**Comment by yohank94** [comment]
@AndyatFocallocal I think it's taking data from team members instead of partners. 

This is what I have after I changed it to use data from Partners. Not sure if you wanna push this change.

![screen shot 2019-03-01 at 3 00 30 pm](https://user-images.githubusercontent.com/22511237/53671367-e33d7d80-3c32-11e9-93c0-8904bc3123bd.png)

**Comment by yohank94** [comment]
Also "Partners" on the page is html coded in the Partners component.

**Comment by AndyatFocallocal** [comment]
Thank you @yohan94! Yes please, push that and I'll work out why Jacques picture isn't working
